### ISSUE TITLE
想知道里面dpz3.dll是干什么用的？能具体描述下它的作用吗

### ISSUE THREAD

**Issue by sunji0peng** [inmount/dotnet-game-opener#1]

**Comment by inmount** [comment]
dpz3.dll是一套提供了些集成算法的.Net Standard基础库，你可以访问dpzsoft/dotnet-dpz3库获取源代码

**Comment by inmount** [comment]
这个项目中主要使用了dpz3.dll中的dpz3.File.ConfFile类进行配置文件(常见的ini文件格式)的读写

**Comment by sunji0peng** [comment]
OK,thanks
